INTRINSICS_STATIC_PATH = 'assets/intrinsics_static.xml'
INTRINSICS_MOVING_PATH = 'assets/intrinsics_moving.xml'
RESULTS_PATH = 'assets/results.xml'
ASSETS_BASE_FOLDER = 'assets/G3DCV2021_data'
ASSETS_STATIC_FOLDER = ASSETS_BASE_FOLDER + '/cam1 - static'
ASSETS_MOVING_FOLDER = ASSETS_BASE_FOLDER + '/cam2 - moving light'

MATCHING_RESULTS_FOLDER_PATH = 'assets/match_results'
TRANSFORMATION_RESULTS_FOLDER_PATH = 'assets/transformation_results'

FPS_STATIC_CAMERA = 30.01
FPS_MOVING_CAMERA = 29.97

ROI_DIAMETER = 400
INTERPOLATION_PARAM = 0.02

# B G R colors
COLOR_BLACK = (0, 0, 0)
COLOR_WHITE = (255, 255, 255)
COLOR_RED = (0, 0, 255)
COLOR_DARK_RED = (0, 0, 128)
COLOR_LIGHT_BLUE = (255, 204, 0)
COLOR_BLUE = (255, 0, 0)
COLOR_PURPLE = (255, 0, 255)
COLOR_YELLOW = (0, 255, 255)
COLOR_GREEN = (0, 255, 0)
COLOR_DARK_GREEN = (0, 51, 0)
COLOR_ORANGE = (0, 102, 255)
