INTRINSICS_STATIC_PATH = 'assets/intrinsics_static.xml'
INTRINSICS_MOVING_PATH = 'assets/intrinsics_moving.xml'
ASSETS_BASE_FOLDER = 'assets/G3DCV2021_data'
ASSETS_STATIC_FOLDER = ASSETS_BASE_FOLDER + '/cam1 - static'
ASSETS_MOVING_FOLDER = ASSETS_BASE_FOLDER + '/cam2 - moving light'

FRAMES_FOLDER_PATH = 'assets/frames'
MATCHING_RESULTS_FOLDER_PATH = 'assets/match_results'
TRANSFORMATION_RESULTS_FOLDER_PATH = 'assets/transformation_results'

MIN_MATCH_KNN = 50
THRESHOLD_KNN = 0.9
MIN_MATCH_FLANN = 25
THRESHOLD_FLANN = 0.8