INTRINSICS_STATIC_PATH = 'assets/intrinsics_static.xml'
INTRINSICS_MOVING_PATH = 'assets/intrinsics_moving.xml'
ASSETS_BASE_FOLDER = 'assets/G3DCV2021_data'
ASSETS_STATIC_FOLDER = ASSETS_BASE_FOLDER + '/cam1 - static'
ASSETS_MOVING_FOLDER = ASSETS_BASE_FOLDER + '/cam2 - moving light'

FRAMES_FOLDER_PATH = 'assets/frames'
MATCHING_RESULTS_FOLDER_PATH = 'assets/match_results'
TRANSFORMATION_RESULTS_FOLDER_PATH = 'assets/transformation_results'

DETECTOR_ALGORITHM_ORB = 'orb'
DETECTOR_ALGORITHM_SIFT = 'sift'

MATCHING_ALGORITHM_BRUTEFORCE = 'bruteforce'
MATCHING_ALGORITHM_KNN = 'knn'
MATCHING_ALGORITHM_FLANN = 'flann'